### ISSUE TITLE
Upgrade to a newer version of Kafka client library

### ISSUE THREAD

**Issue by Kami** [logstash-plugins/logstash-integration-kafka#109]
Right now the plugin is used relatively old version of Kafka client library (v2.5.1).

There are known consensus related bugs which are only fixed in v2.8.1 and v3.0.0 (https://issues.apache.org/jira/browse/KAFKA-12890, https://issues.apache.org/jira/browse/KAFKA-12983, https://issues.apache.org/jira/browse/KAFKA-12984).

We should look at upgrading the Kafka client library to either 2.8.1 or v3.0.0.

I opened a PR which does this in the old logstash-input-kafka repo which is still used in some places (https://github.com/logstash-plugins/logstash-input-kafka/pull/341), but if there is interested, I could work on porting those changes on top of this repo.

**Comment by jsvd** [comment]
Currently the integration ships with kafka client 3.4.1, closing..
