### ISSUE TITLE
Add support for Confluent's Avro Serializers / Deserializers and the Confluent Schema Registry.

### ISSUE THREAD

**Issue by rwaight** [logstash-plugins/logstash-integration-kafka#11]
**Request:**  This is an enhancement request to add support for Confluent's Avro Serializers / Deserializers **_and_** the Confluent Schema Registry.  

**Related issues:**  https://github.com/logstash-plugins/logstash-input-kafka/issues/238 and https://github.com/logstash-plugins/logstash-input-kafka/pull/239

**Products/Versions:**  Logstash 7.5.1, Kafka 2.1.0, logstash-codec-avro 3.2.3, and logstash-integration-kafka 10.0.0

**Additional information:** The specific use-case has SerDes in place and requires access to the Confluent Schema Registry, even if we add the [SerDes](https://docs.confluent.io/current/streams/developer-guide/datatypes.html#data-types-and-serialization) jar (example `kafka-streams-avro-serde-x.y.z.jar`) to the classpath, that would not solve the issue.  We need to add support to access the Confluent Schema Registry.

According the [(still open) PR](https://github.com/logstash-plugins/logstash-input-kafka/pull/239), which is open to add [`the ability to use the KafkaAvroDeserializer directly`](https://github.com/logstash-plugins/logstash-input-kafka/issues/238#issuecomment-386139050).  I also found [this comment](https://github.com/logstash-plugins/logstash-input-kafka/pull/239#commitcomment-26311716) where the originator of the PR states:
> We have been running this logstash plugin with my changes here without any problems. The consumer isn’t throwing any exceptions and is able to use the confluent kafka avro deserializer just fine. Have you tried building/running it and are getting exceptions?

**Comment by andsel** [comment]
This issue is solved by version `10.6.0` of Kafka input from  `logstash-integration-kafka` plugin. The documentation is available at:
https://www.elastic.co/guide/en/logstash-versioned-plugins/current/v10.6.0-plugins-inputs-kafka.html

Essentially the plugin now accepts `schema_registry_url` pointing to a Schema Registry instance, plus it offers proxy settings if there is a proxy in the middle between Logstash and the Schema Registry.
