### ISSUE TITLE
Please add an option for group.instance.id support

### ISSUE THREAD

**Issue by metalshanked** [logstash-plugins/logstash-integration-kafka#117]
Hi 

Kafka static membership is a new feature introduced with Kafka 2.3. It allows the coordinator to persist member identities and to recognize restarted members. This is possible via the consumer configuration `group.instance.id`. If a consumer restarts for any reason, the group coordinator can assign the same partitions to the consumer without rebalancing everything. 

Can we add this very useful option to the Kafka Input Plugin for Logstash?

Thanks in advance!

**Comment by andsel** [comment]
Resolved by #135 shipped with version `11.1.0`
