### ISSUE TITLE
Bump Kafka client to 2.4.0

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-integration-kafka#14]
Related:
https://github.com/logstash-plugins/logstash-output-kafka/issues/232
https://github.com/logstash-plugins/logstash-input-kafka/issues/335

This is a request to bump Kafka client to 2.4.0 (released in Dec 2019)

**Comment by ppf2** [comment]
Pasting discussion from https://github.com/elastic/logstash/issues/11612:

>KIP 392 was merged in the latest Kafka version (2.4).

>The new version reportedly does not break previous functionality, but allows a consumer to read from a replica that is not the leader, but is in sync. This would be useful in cases where there is a highly available Kafka cluster between data centers or regions, where Logstash would then read from the closest dc / region instead of the leader. This saves a lot on network hops.

>Also see https://www.confluent.io/blog/multi-region-data-replication .

>To make full use of the follower fetching functionality, the client.rack parameter needs to be passed to the Kafka Consumer. Besides this, no additional configuration should be needed if the brokers are set up correctly.

>In short, two things would need to be changed about the Logstash Kafka integration:

>- update the org.apache.kafka:kafka-clients dependency to 2.4.0
>- client.rack would need to be added as a param to lib/logstash/inputs/kafka.rb , no changes are needed for the output

**Comment by Duchadian** [comment]
I've opened a [pull request](https://github.com/logstash-plugins/logstash-integration-kafka/pull/16) which should add this feature.

**Comment by roaksoax** [comment]
Closing this issue provided this was resolved since v10.1.0. More details here: https://github.com/logstash-plugins/logstash-input-kafka/issues/335#issuecomment-646068351
