### ISSUE TITLE
Add zstd as acceptable compression type for kafka-output

### ISSUE THREAD

**Issue by immon** [logstash-plugins/logstash-integration-kafka#2]
Please whitelist `zstd` compression type which is [available](https://cwiki.apache.org/confluence/display/KAFKA/KIP-110%3A+Add+Codec+for+ZStandard+Compression) since Kafka 2.1 (we use kafka-clients 2.3.0)

Previous green PR: https://github.com/logstash-plugins/logstash-output-kafka/pull/226/files

**Comment by robbavey** [comment]
This has now been published as `v10.10.0` of the kafka integration plugin
