### ISSUE TITLE
Avoid use of deprecated `poll(long)` method using Kafka 2.x

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-integration-kafka#21]
Currently, the Kafka input uses the deprecated `poll(long)` method, which has been deprecated since `2.0` as part of [this issue](https://cwiki.apache.org/confluence/display/KAFKA/KIP-266%3A+Fix+consumer+indefinite+blocking+behavior).

**Comment by andsel** [comment]
Existing `poll(long)`  method, if necessary, polls also metadata and block in receiving the response. If the broker becomes unresponsive and doesn't return there isn't any timeout on the receive.
The new verision `poll(Duration)` fixes the problem using a timeout in waiting the response of the poll metadata, so if a cluster becomes unresponsive the caller is not blocked on the poll; if the timeout expires it returns.
