### ISSUE TITLE
Do not retry sending messages that failed with a permanent exception

### ISSUE THREAD

**Issue by praseodym** [logstash-plugins/logstash-integration-kafka#27]
The Kafka output plugin will retry messages that failed to send regardless of the exception type, i.e. it will even retry for permanent exceptions (such as a `SerializationException`). By default there is [no limit on the number of retries](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-kafka.html#plugins-outputs-kafka-retries) which means that these kinds of failures indefinitely hang the entire Logstash pipeline.

Fortunately, the Kafka client library already provides a [`RetriableException` base class](https://kafka.apache.org/0110/javadoc/org/apache/kafka/common/errors/RetriableException.html) for exceptions that are retriable (such as a [`TimeoutException`](https://kafka.apache.org/0110/javadoc/org/apache/kafka/common/errors/RetriableException.html)). To prevent the output pipeline from hanging, the retry logic should be adjusted to only retry for exceptions that inherit `RetriableException` and drop (+ log a warning) when the exception is not retriable. This change could be put behind a configuration property to avoid a breaking change.

Prevously reported in https://github.com/logstash-plugins/logstash-output-kafka/issues/178, https://github.com/logstash-plugins/logstash-output-kafka/issues/190, https://github.com/logstash-plugins/logstash-output-kafka/issues/193 and fixed in https://github.com/logstash-plugins/logstash-output-kafka/pull/194 (unmerged PR).

**Comment by GiedriusS** [comment]
This seems pretty critical to me and I ran into this issue myself. Thanks for following up! @jsvd @kares any comments?

**Comment by kares** [comment]
Makes sense, happy to look at any PRs there might be to handle retryable cases better ...

**Comment by praseodym** [comment]
> Makes sense, happy to look at any PRs there might be to handle retryable cases better ...

The PR for this issue in the old repository (https://github.com/logstash-plugins/logstash-output-kafka/pull/194) should still work. I could recreate it on this repository if it has a chance of getting merged.

**Comment by GiedriusS** [comment]
@kares is there a chance of such a PR getting merged?

**Comment by kares** [comment]
Hey Mark (and Giedrius), I am sorry about your previous PR going stale.
If you do not mind porting the changes here please do. 
Having something to start with would be good, can not guarantee we can merge asap as there were some open questions. Still, we definitely need to get thinking about better handling retries.

**Comment by praseodym** [comment]
I recreated the PR in this repository as #29.
