### ISSUE TITLE
Input: make record headers available to events

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-integration-kafka#38]
This is a migration of a feature-request from the stand-alone Input Plugin: https://github.com/logstash-plugins/logstash-input-kafka/issues/336

 - Users want to be able to attach kafka record headers to their events.
 - The record header values are implemented as [arbitrary binary data](https://kafka.apache.org/24/javadoc/org/apache/kafka/common/header/Header.html) and are available via [`org.apache.kafka.clients.consumer.ConsumerRecord#headers`](https://kafka.apache.org/24/javadoc/org/apache/kafka/clients/consumer/ConsumerRecord.html#headers--)

Proposal:
 - migrate `decorate_events` option from boolean to `none`/`basic`/`extended` like we did in the RabbitMQ input to avoid incurring performance penalties when the headers are not explicitly requested https://github.com/logstash-plugins/logstash-integration-rabbitmq/pull/14
 - support only string values that are UTF-8 compatible (including 7-bit ASCII), ignoring others

**Fixed by** : https://github.com/logstash-plugins/logstash-integration-kafka/pull/62

**Comment by RashmiRam** [comment]
@yaauie We are in need of this feature and would like to pick this up. Shall I go ahead and pick this up?

**Comment by andsel** [comment]
@yaauie actually the `decorate_events` options is of `boolean` type, if we move it to the tri-state it changes to `string` type, so we introduce a breaking change I think. How could we manege this without annoy existing user's pipeline configuration? 
My proposal is to keep the existing `decorate_events` as boolean, introduce a new `string` option named `decorate_mode` with the 3 values above. The `decorate_events` is translated to the new `decorate_mode`, then we could warn a deprecation log is the configuration contains the old option.
In case the both new and old options are used, we give precedence to the new warning the clashing.
@yaauie WDYT?

**Comment by yaauie** [comment]
>  if we move it to the tri-state it changes to string type, so we introduce a breaking change

I was a bit lazy in just linking to the other ticket and not fully explaining, but I propose we do it in the same non-breaking way, supporting `true` and `false` inputs as deprecated aliases for `basic` and `none`:

> I changed the formerly boolean `metadata_enabled` to instead accept a value from a list:
> 
> * `none`: no metadata (default)
> * `basic`: header and property metadata
> * `extended`: header, property, and payload metadata
> * `false`: deprecated alias for `none`
> * `true`: deprecated alias for `basic`
> 
> -- https://github.com/logstash-plugins/logstash-integration-rabbitmq/pull/14
