### ISSUE TITLE
Schema registry validation outside of the KafkaConsumer can fail and crash the plugin

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-integration-kafka#72]
This issue has been spawned from a report in https://github.com/logstash-plugins/logstash-integration-kafka/issues/65#issuecomment-772916275:

Depending on how the kafka cluster is secured (using Kerberos, for example), users of the schema registry feature will see the plugin crash since [a schema validation](https://github.com/logstash-plugins/logstash-integration-kafka/blob/72fb752be296d4c5a62c07af081f5dae5c84cb78/lib/logstash/plugin_mixins/common.rb#L32) happens outside of the KafkaConsumer at [plugin register time](https://github.com/logstash-plugins/logstash-integration-kafka/blob/72fb752be296d4c5a62c07af081f5dae5c84cb78/lib/logstash/inputs/kafka.rb#L247-L250):

```ruby
      def check_for_schema_registry_connectivity_and_subjects
        options = {}
        if schema_registry_proxy && !schema_registry_proxy.empty?
          options[:proxy] = schema_registry_proxy.to_s
        end
        if schema_registry_key and !schema_registry_key.empty?
          options[:auth] = {:user => schema_registry_key, :password => schema_registry_secret.value}
        end
        client = Manticore::Client.new(options)

        begin
          response = client.get(@schema_registry_url.to_s + '/subjects').body
        rescue Manticore::ManticoreException => e
          raise LogStash::ConfigurationError.new("Schema registry service doesn't respond, error: #{e.message}")
        end
```

The current workaround is to comment out the validation as described initially in https://github.com/logstash-plugins/logstash-integration-kafka/issues/65#issuecomment-772916275:
 
```ruby
      def check_schema_registry_parameters
        if @schema_registry_url
          check_for_schema_registry_conflicts
          @schema_registry_proxy_host, @schema_registry_proxy_port  = split_proxy_into_host_and_port(schema_registry_proxy)
          check_for_key_and_secret
          # check_for_schema_registry_connectivity_and_subjects
        end
      end
```

A few possible solutions going forward:
1. remove register-time validation and let the plugin fail while consuming
2. disable schema validation when kerberos is configured
3. mirror all possible connection capabilities such as kerberos support in the HTTP client.
4. find a way using existing confluent classes to reuse the KafkaConsumer settings to perform the validation

Option 3 seems quite painful and likely incomplete, and 4 requires investigation to see if it's even possible.

/cc @andsel @fbaligand @gni-icdc

**Comment by fbaligand** [comment]
Up to me, the 4th option is the better one, given that all other access to Kafka are done through java KafkaConsumer.
As you say, 3rd one is the most complex to implement.
The two first ones are very easy to implement.

Anyway, all 4 options fix the issue.

**Comment by robbavey** [comment]
The commit in #97, included in plugin version `10.8.0` has a combination of `#1`, and `#2`, automatically turning off the validation when kerberos is used, and also including a configuration option to skip validation when schema registry validation fails due an auth scheme being used that is unsupported by the validation code path

**Comment by fbaligand** [comment]
Great!

**Comment by fbaligand** [comment]
Given my tests, this works fine now!
So this issue can be closed.
