### ISSUE TITLE
Schema registration authentication methods 

### ISSUE THREAD

**Issue by cmontois** [logstash-plugins/logstash-integration-kafka#89]
I would like to be able to change the authentication method to the schema registry using the following kafka configuration property (basic.auth.credentials.source)
(cf https://docs.confluent.io/platform/current/security/basic-auth.html#schema-registry)

If you want more details about [this](https://stackoverflow.com/questions/67586950/can-not-connect-logstash-to-confluent-schema-registry)
I don't see how i can set this parameters today using this plugin. I need to use USER_INFO instead of URL (set by default [here](https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDeConfig.java#L61)).

**Comment by robbavey** [comment]
I believe this should have been fixed by #94. Can you try upgrading the plugin to the latest version (`10.8.0`)  and see if this works for you.
